name: Hourly Automated Task

on:
  workflow_dispatch:

  schedule:
    - cron: '0 * * * *'

jobs:
  execute-task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Time
        run: |
          echo "Triggered!"
          date -u
          date
